# Generated by Django 2.2.4 on 2022-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20220623_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
        migrations.AddField(
            model_name='list',
            name='users',
            field=models.ManyToManyField(related_name='lists', to='app_one.User'),
        ),
    ]
