# Generated by Django 2.2.4 on 2022-06-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_list_fav_wishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='fav_wishes',
            field=models.ManyToManyField(blank=True, related_name='fav', to='app_one.User'),
        ),
        migrations.RemoveField(
            model_name='list',
            name='users',
        ),
        migrations.AddField(
            model_name='list',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', related_name='lists', to='app_one.User'),
        ),
    ]
