# Generated by Django 2.2.4 on 2022-06-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0006_auto_20220623_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_wishs', models.ManyToManyField(blank=True, related_name='fav_wishes', to='app_one.User')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete='cascade', related_name='wishes', to='app_one.User')),
            ],
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
